### ISSUE TITLE
file模式无法生成文件？

### ISSUE THREAD

**Issue by vencher** [AliyunContainerService/log-pilot#100]
hello,使用file输出模式
命令如下：
`docker run --rm -it     -v /var/run/docker.sock:/var/run/docker.sock     -v /:/host -v /etc/localtime:/etc/localtime  -e FLUENTD_OUTPUT=file -e FLUENTD_FLUSH_MODE=immediate -e FILE_PATH=/data/logs    --privileged     registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.1`
但是不管是宿主机还是容器内/data/logs下无法找到。

**Comment by crystonesc** [comment]
我试了下，我的可以呢，是在容器里面的目录里

**Comment by vencher** [comment]
请问是以我得命令执行的吗？

**Comment by vencher** [comment]
重新又试了一下，仍然是没有看到又日志文件输出。

**Comment by crystonesc** [comment]
FLUENTD_FLUSH_MODE=immediate 
 -v /etc/localtime:/etc/localtime
我的命令没加这个，但是应该不影响吧
FILE_PATH=/data/logs 你的log_pilot里面有这个目录么

**Comment by vencher** [comment]
容器里面没有这个目录。后面我尝试通过-v /data/logs:/data/logs进行挂载。

**Comment by vencher** [comment]
是否我验证的方式有问题？请问您验证的命令是如何的?

**Comment by vencher** [comment]
明白了，用了你的代码是可以执行的。我一直跑的都是0.1的版本，因为在下载0.3，0.2下载不到。并没有使用latest版本

**Comment by vencher** [comment]
谢谢。

**Comment by crystonesc** [comment]
我也遇到一堆问题，没人回复...

**Comment by vencher** [comment]
相互学习了。
