### ISSUE TITLE
采集的日志通过filebeat plugin写到kafka,怎么配置多个broker以及端口，还有指定topic

### ISSUE THREAD

**Issue by crystonesc** [AliyunContainerService/log-pilot#101]
docker run --rm -d \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v /:/host \
   -e PILOT_TYPE=filebeat \
   -e FILEBEAT_OUTPUT=kafka \
   -e KAFKA_BROKERS="1.1.1.1:6667","2.2.2.2:6667","3.3.3.3:6667" \
   --privileged \
   registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest

这样写要报错，还有如何指定topic呢

**Comment by chenqz1987** [comment]
env:
          - name: "FILEBEAT_OUTPUT"
            value: "kafka"
          - name: "KAFKA_BROKERS"
            value: "kafka1:9092,kafka2:9092"

**Comment by chenqz1987** [comment]
topic可以通过在tags里指定topic=xxx的方式即可

**Comment by crystonesc** [comment]
docker run --rm -d \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /:/host \
        -e PILOT_TYPE=filebeat \
        -e FILEBEAT_OUTPUT=kafka \
        -e KAFKA_BROKERS="\"133.38.35.31:6667\",\"133.38.35.32:6667\",\"133.38.35.33:6667\"," \
	--privileged \
	registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
我试了下，要用转移符把引号加上才行的哇

**Comment by crystonesc** [comment]
另外想问下，topic 的指定是在启动tomcat的--label aliyun.logs.$name.tags="topic=xxx"来指定么，我这样做了好像不行

**Comment by chenqz1987** [comment]
是这样指定的

**Comment by crystonesc** [comment]
好的，谢谢

**Comment by chengzixs** [comment]
请问下 这个样配置topic有没有解决问题呢
