### ISSUE TITLE
log-pilot获取的日志信息，如果将宿主机的信息带上

### ISSUE THREAD

**Issue by crystonesc** [AliyunContainerService/log-pilot#104]
按照默认，收集到的tomcat的日志信息，只包括了容器的名称，如何能够把宿主机的信息也带上呢

**Comment by chenqz1987** [comment]
需要带宿主机的哪些信息？

**Comment by crystonesc** [comment]
比如宿主机的主机名、IP地址。这样的话，在定位日志的时候，才能根据宿主机+容器的名称定位具体的容器位置

**Comment by chenqz1987** [comment]
目前宿主机的主机名可以通过设置环境变量NODE_NAME来支持，这样在采集日志时可以取到一起放到日志里
