### ISSUE TITLE
log-pilot多副本的情况怎么处理

### ISSUE THREAD

**Issue by yu-yang2** [AliyunContainerService/log-pilot#112]
测试deployment多实例的情况下, 只能读取一个副本的日志, 这种情况怎么处理呢?

**Comment by yu-yang2** [comment]
[https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/](url) 用pod名称只能用作 env 的 value, 不能用作 env 的 name

**Comment by chenqz1987** [comment]
您的deployment多实例都是在一个node上吗？另外配置的volume是emptydir还是host path bind？

**Comment by yu-yang2** [comment]
@chenqz1987 多实例是挂载emptyDir, 有可能在同一节点上,但是emptyDir在同节点上面挂载的目录是不同的, 应该不影响吧.

**Comment by yu-yang2** [comment]
deployment多副本的情况是不支持么? 还是需要什么特殊配置?

**Comment by chenqz1987** [comment]
@yu-yang2 emptyDir是支持的，不影响，您是使用的filebeat插件吧？可以看下log-pilot内部/etc/filebeat/prospectors.d/目录下这个容器的配置里配置的是否正确？

**Comment by yu-yang2** [comment]
@chenqz1987 是用的 filebeat, 但是log-pilot 用环境变量来标识收集对象, 多实例的情况下根本区分不了吧?

**Comment by pdjdyeyffdx** [comment]
deployment多副本日志写入GFS，所有副本的日志都在一个目录中，使用logpilot配置会重负拉取日志么？

**Comment by chenquanzhao** [comment]
@pdjdyeyffdx 不会的
