### ISSUE TITLE
master分支上Dockerfile制作出来的镜像无法推送数据到es

### ISSUE THREAD

**Issue by edgar1992** [AliyunContainerService/log-pilot#117]
通过master分支的Dockerfile.fluentd制作出来的镜像无法推送数据至es，但是文档中提供的打了latest标签的镜像可以推送，请问这两个Dockerfile有什么区别吗，代码中是否有提供latest标签镜像的Dockerfile？
而且两个镜像的fluentd版本不一致，latest标签中fluentd版本是1.0.2，但是根据master分支制作出来的镜像fluentd版本是1.2.1。

**Comment by chenqz1987** [comment]
无法推送到es，有具体的报错信息吗？
另外master分支里Dockerfile.fluentd里指定安装的fluentd version是1.1.0，可以确认下您拉下来的master分支里的Dockerfile.fluentd里配置的version

**Comment by edgar1992** [comment]
有可能是我用的es的版本(5.6.4)引起的。
报错：Field [_timestamp] is a metadata field and cannot be added inside a document. 
pilot.go 这个文件的第575行cfg.FormatConfig["time_key"] = "_timestamp" ，我把这里的下划线去掉后没再报这个错

**Comment by dongyupu** [comment]
es7.1.0
log-pilot 0.9.7-fluentd
stdout 可以正常写入到es，指定文件的不行，报错和edgar1992  的一样，按照 edgar1992 的方式修改 cfg.FormatConfig["time_key"] = "_timestamp"后重新编译就可以了
