### ISSUE TITLE
是否可以提供官方镜像的构建脚本？

### ISSUE THREAD

**Issue by wangruochan** [AliyunContainerService/log-pilot#118]
按照README中的说明，没有找到这个build.sh文件

```
go get github.com/AliyunContainerService/log-pilot
cd $GOPATH/github.com/AliyunContainerService/log-pilot/docker-images
./build.sh # This will create a new docker image named pilot:latest
```

**Comment by chenqz1987** [comment]
@wangruochan 直接通过项目根目录下的Dockerfile.filebeat或者Dockerfile.fluentd构建下就可以，我更新下doc说明

**Comment by wangruochan** [comment]
感谢答复。
Dockerfile.filebeat构建的镜像只能使用filebeat，Dockerfile.fluentd构建的镜像只能使用fluentd。我看官方的镜像貌似融合了两个dockerfile，想学习下脚本是如何写的

**Comment by chenqz1987** [comment]
后面打包我们也是分开的了，可以依据您的需求使用一种即可

**Comment by wangruochan** [comment]
好的，感谢
