### ISSUE TITLE
[help] 如何提升采集频率？

### ISSUE THREAD

**Issue by zzswang** [AliyunContainerService/log-pilot#120]
试图提升采集频率，求教配置项

如果直接打印到 控制台，大约是延时5~6s，有点慢。想提升一下采集频率

**Comment by chenqz1987** [comment]
@zzswang 是通过log-pilot输出到控制台？您使用的是fluentd还是filebeat？可以看到对应的fluentd或者filebeat配置文件是否有buffer之类的配置项？

**Comment by zzswang** [comment]
我现在把 interval 改成 1 秒。

但是它有个 immediate 模式，貌似不起作用

**Comment by chenqz1987** [comment]
可否贴下生成出来的配置看下

**Comment by zzswang** [comment]
原因应该是这个

reference #119 

关闭这个 issue
