### ISSUE TITLE
该项目是否支持其他云服务器部署？

### ISSUE THREAD

**Issue by wjzhangcsu** [AliyunContainerService/log-pilot#122]
偷个懒，就直接来提问了，由于各种原因，公司服务需要在多个云服务器上部署，请问该项目是否支持其他云服务器部署？另外请教个其他问题，之前在听k8smeetup的讲座的时候，全照大神说filebeat的采集速度比fleuntd快很多，实测并没有。请问具体的测试方法是怎么样的呢？

**Comment by chenqz1987** [comment]
可以部署的；我们测试一种场景是事先准备好一个很大的日志文件，然后定制了一个特定的输出，仅仅只是用来计数下，这样来对比测试；另一种是边产生日志边采集

**Comment by wjzhangcsu** [comment]
首先感谢回答～突然发现自己的问的问题有点问题，可以部署是只阿里云、华为云、腾讯云都可以部署哈？
