### ISSUE TITLE
--label aliyun.logs.catalina=stdout \ 并未收集到tomcat打印到控制台的日志

### ISSUE THREAD

**Issue by crystonesc** [AliyunContainerService/log-pilot#124]
tomcat容器里面通过catalina.sh run启动服务，日志全部输出到控制台，log-pilot通过 --label aliyun.logs.catalina=stdout这个标签来收集控制台的日志，但是并没有收集成功?

**Comment by chenqz1987** [comment]
可以看下Log-pilot容器内部是否有生成tomcat容器的采集配置文件

**Comment by chenqz1987** [comment]
另外您使用的log-pilot 镜像是哪个？

**Comment by crystonesc** [comment]
我后来发现了问题，我的docker环境日志是输出到Journald，所以log-pilot就采集不到了，要更改成json-file才行

**Comment by wajika** [comment]
> 可以看下Log-pilot容器内部是否有生成tomcat容器的采集配置文件

有点搞混了 在K8S下是在--env增加aliyun_logs_nginxaccesslog=stdout 还是加--labels=aliyun_logs_nginxaccesslog=stdout？
