### ISSUE TITLE
不能输出stdout日志

### ISSUE THREAD

**Issue by yixiua** [AliyunContainerService/log-pilot#125]
rancher中起了一个 tomcat 将日志输出到ES。
但只是自动创建access 索引，stdout 要输出的catalina索引没有创建。
下面是我的搭建和日志信息：
        **pilot：**
`pilot:
  image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
  environment:
    ELASTICSEARCH_HOST: 1.1.1.1
    ELASTICSEARCH_PORT: '9200'
    ELASTICSEARCH_USER: user
    ELASTICSEARCH_PASSWORD: pw
    FLUENTD_OUTPUT: elasticsearch
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /:/host
  labels:
    aliyun.global: 'true'

**/etc/fluentd/conf.d 里面也有catalina的。**
<filter docker.7e2fbdf54de4646ce83ffad0bda4d22a33d0588c8aa95b4391fd2aeb3036f520.catalina>
  @type record_transformer
  enable_ruby true
  <record>
    host "#{Socket.gethostname}"
    index catalina
    topic catalina
    @target catalina-${time.strftime('%Y.%m.%d')}
    docker_container r-app-myweb-1-8636c928
  </record>
</filter>

           
          **tomcat:**
Volumes:   /usr/local/tomcat/logs
labels:    aliyun.logs.catalina=stdout
              aliyun.logs.access=/usr/local/tomcat/logs/localhost_access_log.*.txt`
           **pilot log：**
**log1:**
2018/6/14 下午5:10:37    <inject>
2018/6/14 下午5:10:37      time_key @timestamp
2018/6/14 下午5:10:37    </inject>
2018/6/14 下午5:10:37  </filter>
2018/6/14 下午5:10:37  <filter docker.7e2fbdf54de4646ce83ffad0bda4d22a33d0588c8aa95b4391fd2aeb3036f520.catalina>
2018/6/14 下午5:10:37    @type record_transformer
2018/6/14 下午5:10:37    enable_ruby true
2018/6/14 下午5:10:37    <record>
2018/6/14 下午5:10:37      host 43434cb2984b
2018/6/14 下午5:10:37      index catalina
2018/6/14 下午5:10:37      topic catalina
2018/6/14 下午5:10:37      @target catalina-${time.strftime('%Y.%m.%d')}
2018/6/14 下午5:10:37      docker_container r-app-myweb-1-8636o928
2018/6/14 下午5:10:37    </record>
2018/6/14 下午5:10:37  </filter>
2018/6/14 下午5:10:37  <match docker.**>
2018/6/14 下午5:10:37    @type elasticsearch
2018/6/14 下午5:10:37    hosts "1.1.1.1:9200"
2018/6/14 下午5:10:37    reconnect_on_error true
2018/6/14 下午5:10:37    user "user"
2018/6/14 下午5:10:37    password xxxxxx
2018/6/14 下午5:10:37    target_index_key "@target"
2018/6/14 下午5:10:37    type_name "fluentd"
2018/6/14 下午5:10:37  </match>
2018/6/14 下午5:10:37</ROOT>

Erro log:
P1:
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:692:in `readpartial'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:692:in `block in on_notify'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:751:in `with_io'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:685:in `on_notify'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:534:in `on_notify'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:507:in `attach'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:264:in `setup_watcher'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:292:in `block in start_watchers'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:278:in `each'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:278:in `start_watchers'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:258:in `refresh_watchers'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/in_tail.rb:193:in `start'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:165:in `block in start'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:154:in `block (2 levels) in lifecycle'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `each'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:153:in `block in lifecycle'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `each'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:140:in `lifecycle'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/root_agent.rb:164:in `start'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:274:in `start'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/engine.rb:219:in `run'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:774:in `run_engine'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:523:in `block in run_worker'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:699:in `main_process'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/supervisor.rb:518:in `run_worker'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/bin/fluentd:8:in `<top (required)>'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/bin/fluentd:22:in `load'
2018/6/14 下午5:10:37  2018-06-14 09:10:37 +0000 [error]: #0 /usr/bin/fluentd:22:in `<main>'

P2:
2018/6/14 下午5:09:182018-06-14 09:09:18 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2018/6/14 下午5:09:18  2018-06-14 09:09:18 +0000 [error]: #0 suppressed same stacktrace
2018/6/14 下午5:09:192018-06-14 09:09:19 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2018/6/14 下午5:09:19  2018-06-14 09:09:19 +0000 [error]: #0 suppressed same stacktrace
2018/6/14 下午5:09:202018-06-14 09:09:20 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2018/6/14 下午5:09:20  2018-06-14 09:09:20 +0000 [error]: #0 suppressed same stacktrace
2018/6/14 下午5:09:212018-06-14 09:09:21 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2018/6/14 下午5:09:21  2018-06-14 09:09:21 +0000 [error]: #0 suppressed same stacktrace

**Comment by chenqz1987** [comment]
@yixiua 使用registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.3-filebeat这个image看看

**Comment by tangxy** [comment]
参考： https://helpcdn.aliyun.com/document_detail/68264.html?spm=a2c4g.11186623.6.643.LhFBJ6 这个里面的配置，   能够收集到access的日志， 但是stdout的日志也收集不到。

镜像替换成：registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.3-filebeat 后也是同样的问题。

**Comment by tangxy** [comment]
log-pilot中的配置容器采集配置如下：

/etc/filebeat/prospectors.d # cat 75f71f957d2f28537ba52423a1e80a354bac42b42541fa08a2d22a267b4c8169.yml 

- type: log
  enabled: true
  paths:
      - /host/var/lib/kubelet/pods/edd712d3-8cd7-11e8-b04f-005056861d76/volumes/kubernetes.io~empty-dir/accesslogs/localhost_access_log.*.txt
  scan_frequency: 10s
  fields_under_root: true
  
  
  fields:
      
      index: access
      
      topic: access
      
      
      docker_container: k8s_cuckoo-web_cuckoo-web-589466c59f-kcjtg_vsit_edd712d3-8cd7-11e8-b04f-005056861d76_0
      
      k8s_container_name: cuckoo-web
      
      k8s_pod: cuckoo-web-589466c59f-kcjtg
      
      k8s_pod_namespace: vsit
      
  tail_files: false
  close_inactive: 2h
  close_eof: false
  close_removed: true
  clean_removed: true
  close_renamed: false


- type: log
  enabled: true
  paths:
      - /host/.*
  scan_frequency: 10s
  fields_under_root: true
  
  docker-json: true
  
  
  fields:
      
      index: catalina
      
      topic: catalina
      
      
      docker_container: k8s_cuckoo-web_cuckoo-web-589466c59f-kcjtg_vsit_edd712d3-8cd7-11e8-b04f-005056861d76_0
      
      k8s_container_name: cuckoo-web
      
      k8s_pod: cuckoo-web-589466c59f-kcjtg
      
      k8s_pod_namespace: vsit
      
  tail_files: false
  close_inactive: 2h
  close_eof: false
  close_removed: true
  clean_removed: true
  close_renamed: false

**Comment by tangxy** [comment]
上述问题已解决：
        目前集群中的docker版本：1.13.1 ， 他默认使用的log driver是“journald” 因此无法采集stdout日志。
        参考：https://segmentfault.com/a/1190000014559152 中的方法，将log driver 修改为 json-file 
        如果 systemctl restart docker 报错， 可将  /var/run/docker.sock 文件（夹）删除后再重启
