### ISSUE TITLE
收集发送到elasticsearch中日志乱序

### ISSUE THREAD

**Issue by yuxing1994** [AliyunContainerService/log-pilot#127]
前后顺序乱了

**Comment by yuxing1994** [comment]
是写入elas的时间戳问题, 请问如何设置写入微秒

**Comment by zjzhangkui** [comment]
@yuxing1994 请问这个有解决吗？

**Comment by ChenBilong** [comment]
可以通过offset排序

**Comment by yuxing1994** [comment]
@zjzhangkui  解决了我是直接修改这个log-pilot的收集，加入了一个微妙字段，用ruby获取微秒。
@chenquanzhao  是通过elk offset排序是吧，请问怎么做的，如果都是毫秒，基本上下顺序排不好吧
