### ISSUE TITLE
不支持一个容器采集多个路径下的日志

### ISSUE THREAD

**Issue by zjzhangkui** [AliyunContainerService/log-pilot#131]
在k8s集群运行容器，如果某个容器有多个日志路径，想采集到elasticsearch同一个index中，目前设置方式不支持多路径，不能多个路径以逗号分割。
        - name: aliyun_logs_logstash
          value: "/usr/local/tomcat/logs/catalina.*.log,/var/log/*.log"
这个可否支持？

**Comment by chenquanzhao** [comment]
@zjzhangkui 这个后续考虑支持，目前的话可以将日志输出在同一个日志目录下，通过不同的日志文件名来区分

**Comment by flapjackegg** [comment]
同样遇到这个问题了？有计划什么时候正式支持此功能吗

**Comment by bogeit** [comment]
> 同样遇到这个问题了？有计划什么时候正式支持此功能吗

同问，现在pod里面的业务日志是写在两处不同的路径下，没办法弄到一个目录里面的。

**Comment by bogeit** [comment]
> @zjzhangkui 这个后续考虑支持，目前的话可以将日志输出在同一个日志目录下，通过不同的日志文件名来区分

那env传入是这样的写的嘛（同一目录路径下，不同的日志名称）：   @chenquanzhao 

env:
    - name: aliyun_logs_catalina
      value: "stdout"
    - name: aliyun_logs_access
      value: "/usr/local/tomcat/logs/catalina.*.log"
    - name: aliyun_logs_error
      value: "/usr/local/tomcat/logs/error.*.log"

**Comment by chenquanzhao** [comment]
@bogeit 可以是同一个目录不同的日志文件名，或者是不同的日志目录都可以
