### ISSUE TITLE
json-file仍无法获取stdout，使用本地仓库的镜像添加不了index

### ISSUE THREAD

**Issue by AisakaTaiga** [AliyunContainerService/log-pilot#132]
docker版本1.18，Logging Driver: json-file，但仍无法获取标准输出。
尝试以一个本地镜像启动，添加
 env:
     - name: aliyun_logs_nginxtest                                 
       value: "stdout"    
在ES中未见nginxtest这个index

**Comment by chenquanzhao** [comment]
@AisakaTaiga 可以先确认下log-pilot是否生成对应容器的日志采集配置文件

**Comment by wajika** [comment]
> @AisakaTaiga 可以先确认下log-pilot是否生成对应容器的日志采集配置文件
怎么查看 log-pilot已经生成了对应容器的日志采集配置文件？
