### ISSUE TITLE
log-pilot encoding error

### ISSUE THREAD

**Issue by opera443399** [AliyunContainerService/log-pilot#133]
**images I'v used**
---
[weeks ago]
```bash
~]# docker images |grep pilot 
registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot        latest              5a4655c50fdc        6 months ago        147MB
```

[now]
```bash
~]# docker images |grep pilot 
registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot        0.9.5-fluentd       5d135401ace8        6 days ago          99.3MB
```

> both of this 2 versions will print errors like this:

```bash
 ~]# docker logs -f --tail 20 log-pilot
2018-07-31 11:32:15 +0800 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-07-31 11:32:13 +0800 chunk="5724339000756af64a7155511b5e078c" error_class=Encoding::UndefinedConversionError error="\"\\xE9\" from ASCII-8BIT to UTF-8"
```

**question**
---
how to fix this?  I'm not familiar with ruby.

**Comment by chenquanzhao** [comment]
@opera443399 It seems like an encoding problem, and you can try to use 0.9.5-filebeat image

**Comment by opera443399** [comment]
@chenquanzhao as I'v mentioned above, `both of this 2 versions will print errors...`

**Comment by chenquanzhao** [comment]
@opera443399 I mean the image tag is  0.9.5-filebeat instead of  0.9.5-fluentd

**Comment by opera443399** [comment]
@chenquanzhao 
so, the image tag `0.9.5-filebeat` also include fluentd inside this image? Or, I have to use filebeat to replace fluentd as my new log agent?

**Comment by chenquanzhao** [comment]
@opera443399 yeah, you can just use filebeat to collect your container logs

**Comment by opera443399** [comment]
@chenquanzhao Please let me know how to replace it?

**fluentd**
```bash
docker run -d --rm -it \
    --name logs-agent \
    -v /etc/localtime:/etc/localtime \
    -v /etc/timezone:/etc/timezone \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /:/host \
    --privileged \
    -e PILOT_TYPE="fluentd" \
    -e FLUENTD_OUTPUT="graylog" \
    -e GRAYLOG_HOST="10.50.200.101" \
    -e GRAYLOG_PORT="12201" \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.5-fluentd
```

**Comment by opera443399** [comment]
@chenquanzhao 

What I want it:
`fluentd+graylog` -> `filebeat+graylog`

I have no idea which env should I choose.

just replace the keyword like this?
FROM:
```
    -e PILOT_TYPE="fluentd" \
    -e FLUENTD_OUTPUT="graylog" \
```
TO:
```
    -e PILOT_TYPE="filebeat" \
    -e FILEBEAT_OUTPUT="graylog" \
```

**Comment by chenquanzhao** [comment]
@opera443399 sorry, if need to collect logs to graylog, it still use fluentd plugin. 

> 018-07-31 11:32:15 +0800 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-07-31 11:32:13 +0800 chunk="5724339000756af64a7155511b5e078c" error_class=Encoding::UndefinedConversionError error="\"\\xE9\" from ASCII-8BIT to UTF-8"

it seems a fluentd encoding bug：https://github.com/fluent/fluentd/issues/215，and we will try to fix it, or maybe a PR from you will be welcomed.
