### ISSUE TITLE
aliyun.logs.$name.format参数配置没起到作用？

### ISSUE THREAD

**Issue by haoyangyi** [AliyunContainerService/log-pilot#134]
docker run -it --rm  -p 10080:8080 \
    -v /usr/local/tomcat/logs \
    --label aliyun.logs.access=/usr/local/tomcat/logs/localhost_access_log.*.txt \
    --label aliyun.logs.access.format=none \
    tomcat

**Comment by haoyangyi** [comment]
简单修改该参数查看日志格式输出发现没有改变，用的是 filebeat模式

**Comment by glwlg** [comment]
这个是告诉log-pilot你的日志是什么格式
不是改变格式

**Comment by haoyangyi** [comment]
我还以为是改变格式呢
