### ISSUE TITLE
log-pilot是否支持多个容器部署同一宿主机协同工作

### ISSUE THREAD

**Issue by haoyangyi** [AliyunContainerService/log-pilot#136]
log-pilot看文档是单容积部署宿主机的，存在单点故障，想知道log-pilot是否支持多个容器部署同一宿主机，一个容积挂了其他容器能够继续稳定工作。

**Comment by glwlg** [comment]
--restart=always不就可以了?

**Comment by haoyangyi** [comment]
兄弟留下联系方式交流一波，最近搞k8s日志采集
