### ISSUE TITLE
Log output plugin是否支持获取环境和label变量

### ISSUE THREAD

**Issue by haoyangyi** [AliyunContainerService/log-pilot#137]
比如我采集容器日志到flie，但是是多个不同业务的容器，FILE_PATH和FILE_NAME我相动态根据label配置，
比如2个容器分别运行A和B服务，但是我向将A和B分别采集到不同路径的不同文件下。可以类似这样配置
FILE_PATH=/opt/log/${topic}/${container},FILE_NAME=${container}-YYYY-MM-dd。现在我看file output都是所有都写一个目录的一个文件，有办法多目录多文件用于做到不同服务不同容器日志的完全隔离？？

**Comment by chenquanzhao** [comment]
目前由于filebeat本身还不支持
