### ISSUE TITLE
： RRO[0000] fail to process container /r-ddslack-aws-online-slack-1-44fb53eb: ddslack-trace has no parent node

### ISSUE THREAD

**Issue by kangjianhua** [AliyunContainerService/log-pilot#139]
使用这个 镜像  registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot  ：
报错如下 ：
RRO[0000] fail to process container /r-ddslack-aws-online-slack-1-44fb53eb: ddslack-trace has no parent node
不知道有人遇到吗？

**Comment by chenquanzhao** [comment]
使用的镜像tag是？
