### ISSUE TITLE
请问如何使用log-pilot采集日志通过网络远程传输到本机？

### ISSUE THREAD

**Issue by chenlinOne** [AliyunContainerService/log-pilot#147]
现在有个需求需要通过log-pilot采集远程容器中的日志通过公网发送的本机，请问要如何配置？

**Comment by chenquanzhao** [comment]
@chenlinOne log-pilot是通过采集本节点容器日志文件的方式采集的，无法从本地采集到远程的容器，您可以将Log-Pilot部署在目标容器的节点上可以来采集日志

**Comment by chenlinOne** [comment]
@chenquanzhao 请问Log-Pilot中有没有API可以直接通过http查看收集日志的内容？

**Comment by chenquanzhao** [comment]
#149
