### ISSUE TITLE
容器启动报错

### ISSUE THREAD

**Issue by Yanbuc** [AliyunContainerService/log-pilot#152]
我的命令：
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /:/host:ro \
    -e PILOT_TYPE=fluentd \
    -e LOGGING_OUTPUT=file \
    -e FILE_PATH="/usr/local/src" \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest

我的报错：
![qq](https://user-images.githubusercontent.com/28927682/46902079-657e0d00-cef1-11e8-9312-2c1cb52c3ca7.PNG)

问题：1：我的操作有什么错误吗？
2： 除了 github 还有其他的地方有文档吗？

**Comment by Yanbuc** [comment]
文档上面的例子在我的电脑上也不能运行
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /:/host:ro \
    -e PILOT_TYPE=fluentd \
    -e LOGGING_OUTPUT=elasticsearch \
    -e ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST} \
    -e ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT} \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:latest
好像是在阿里的文档上面发现的 下面的命令是可以运行的
docker run --rm -it \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /:/host:ro \
    -e PILOT_TYPE=fluentd \
    -e LOGGING_OUTPUT=file \
    -e FILE_PATH="/usr/local/src/a.txt" \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.5-fluentd

**Comment by Yanbuc** [comment]
log-pliot 使用fluentd 插件 下面的命令 是能跑起来的
docker run --rm -it --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /:/host:ro \
    -e PILOT_TYPE=fluentd \
    -e LOGGING_OUTPUT=file \
    -e FILE_PATH=/usr/local/src/dd\
    -e FLUENTD_BUFFER_TYPE=file \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.5-fluentd

**Comment by Yanbuc** [comment]
github文档上面的例子 是不是 有点过时了？

**Comment by chenquanzhao** [comment]
@Yanbuc 嗯，感谢反馈，我们更新下doc

**Comment by buhe** [comment]
运行可以，不过没有看到收集完的日志， @Yanbuc 请问你那边在 /usr/local/src 下面有日志吗？

**Comment by chenquanzhao** [comment]
@Yanbuc 文档已更新，感谢反馈!
