### ISSUE TITLE
按照例子取tomcat access日志字段问题

### ISSUE THREAD

**Issue by hejiazhen1203** [AliyunContainerService/log-pilot#153]
es报错如：failed to execute bulk item (index) BulkShardRequest [[access-2018.10.30][0]] containing [index {[access-2018.10.30][fluentd][AWbC7uVVLawF0Y3wsVtX], source[{"message":"172.30.192.145 - - [30/Oct/2018:03:04:15 +0000] \"GET / HTTP/1.1\" 200 11286","_timestamp":"2018-10-30T03:04:23.717","host":"9c31d1a33131","index":"access","topic":"access","docker_container":"happy_khorana"}]}]
org.elasticsearch.index.mapper.MapperParsingException: Field [_timestamp] is a metadata field and cannot be added inside a document. Use the index API request parameters.

**Comment by chenquanzhao** [comment]
@hejiazhen1203 您跑的是哪个例子，我这边看下

**Comment by hejiazhen1203** [comment]
registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.6-fluentd用的这个镜像，然后测试了tomcat的日志，stdout日志是成功导入ES了，access的文件日志在ES中只生成了生成了对应的索引，日志内容没成功写入，报错如上描述

**Comment by chenquanzhao** [comment]
@hejiazhen1203 这个问题我们详细看下，当前您要采集日志到ES，可以使用0.9.6-filebeat镜像
