### ISSUE TITLE
Swarm cannot run registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.6-fluentd

### ISSUE THREAD

**Issue by o451** [AliyunContainerService/log-pilot#154]
I want to run registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.6-fluentd in swarm, to collect logs and save to aliyun log service.
But swarm cannot set "--cap-add SYS_ADMIN" property, which cause the image cannot run in swarm. Is there anything I can do to run it in swarm mode? Thanks.
My compose file is as follows (cap_add was ignored when starting up swarm):
version: '3.6'
services:
  logger:
    image: registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.6-fluentd
    environment:
      LOGGING_OUTPUT: 'aliyun_sls'
      ALIYUNSLS_ACCESS_KEY_ID: 'XXXXX'
      ALIYUNSLS_ACCESS_KEY_SECRET: 'XXXXX'
      ALIYUNSLS_PROJECT: 'mycontainerlogproject'
      ALIYUNSLS_REGION_ENDPOINT: 'cn-qingdao.log.aliyuncs.com'
      ALIYUNSLS_NEED_CREATE_LOGSTORE: 'true'
      ALIYUNSLS_CREATE_LOGSTORE_TTL: '2'
      ALIYUNSLS_CREATE_LOGSTORE_SHARD_COUNT: '2'
      SSL_VERIFY: 'true'
    cap_add:
      - SYS_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host

**Comment by chenquanzhao** [comment]
@o451 Yeah. It does not support cap_add in v3 compose. Maybe you can deploy v2 compose or docker run directly.
