### ISSUE TITLE
fluentd 延迟

### ISSUE THREAD

**Issue by hunshenshi** [AliyunContainerService/log-pilot#159]
使用fluentd利用time来切分日志，发现日志有延迟，有些日志在buffer中，归档有点延迟，大家有遇到过吗？ 调了些参数，但感觉还是会延迟

**Comment by chenquanzhao** [comment]
@hunshenshi 是否配置了

**Comment by chenquanzhao** [comment]
@hunshenshi 尝试配置FLUENTD_FLUSH_MODE为immediate，fluentd配置参考https://docs.fluentd.org/v1.0/articles/buffer-section

**Comment by hunshenshi** [comment]
@chenquanzhao  我需要使用time的特性，所以不能用immediate，你们用的是filebeat？没有使用fluentd？还有就是我打算让log-pilot支持flume，你们有这个计划不？

**Comment by chenquanzhao** [comment]
@hunshenshi 我们依据不同场景会用不同的plugin；暂未计划支持flume，主要考虑到flume太重了

**Comment by hunshenshi** [comment]
我开发了个flume plugin，个人感觉flume要好用很多，也比较灵活 @chenquanzhao
