### ISSUE TITLE
无法获取tags

### ISSUE THREAD

**Issue by lvelvis** [AliyunContainerService/log-pilot#160]
日志先输出到kafka，然后再logstash消费日志到es集群，输出结果里没有分配的tags     
 containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: aliyun_logs_loginsucess
            value: "/usr/local/nginx/html/login/runtime/logs/login_succ.json"
          - name: aliyun.logs.loginsucess.tags
            value: "stage=dev"
          - name: aliyun.logs.loginsucess.format
            value: "json"

tags  输出到es无法获取到stage=dev

**Comment by lvelvis** [comment]
- name: aliyun_logs_loginsucess_tags
  value: "stage=dev"
这样才可以 是否考虑过同一个容器多日志，多个tags区分不同日志呢
`- input_type: log
  paths:
    - /var/logs/login_succ.json*
  exclude_files: [".md5$"]
  tags: ["k8s-common-login-succ-dev"]
  ignore_older: 48h
  close_inactive: 12h
  clean_inactive: 72h
filebeat.registry_file: /etc/filebeat/k8s-common-login-succ-dev.pos
output.kafka:
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
  indices:
    when.contains:
      log_type: k8s-common-login-succ-dev`

**Comment by chenquanzhao** [comment]
> - name: aliyun.logs.loginsucess.tags
value: "stage=dev"
> - name: aliyun.logs.loginsucess.format
value: "json"

@lvelvis ENV 里通过下划线_的配置方式

**Comment by lvelvis** [comment]
谢谢 解决了
