### ISSUE TITLE
access=/opt/conpot/logs/localhost_access_log has no parent node

### ISSUE THREAD

**Issue by zhangxiaoyus** [AliyunContainerService/log-pilot#161]
我通过 docker Python sdk Api执行相当于docker run -itd --rm  -p 1008:80     -v /usr/local/tomcat/logs     --label aliyun.logs.catalina=stdout     --label aliyun.logs.es_access=/usr/local/conpot/logs/localhost_access_log.*.txt   conpot_http
的命令，出现这个报错，请问这是什么导致的

ERRO[0401] fail to process event: {start 15ef7509e3fcf42ab8ba3b3e04c2929abedb3d7d2f822362991356c0d22e9603 conpot_http container start {15ef7509e3fcf42ab8ba3b3e04c2929abedb3d7d2f822362991356c0d22e9603 map[aliyun.logs.access=/opt/conpot/logs/localhost_access_log.*.txt: aliyun.logs.catalina=stdout: image:conpot_http name:conpot_http]} local 1544869120 1544869120412818229},  access=/opt/conpot/logs/localhost_access_log has no parent node

**Comment by anarckk** [comment]
我下午终于找到解决方法了
```
xxx_logs_java  可以
xxx_logs_java_11  不行
xxx_logs_java_1  不行
xxx_logs_java_  不行
xxx_logs_javae  可以
xxx_logs_javazzzzzzzzzzzzz  可以
xxx_logs_java11  可以
```
所以，是命名问题
