### ISSUE TITLE
k8s 环境下使用fluentd采集log，pod中容器重启之后是不是容易造成日志重复采集

### ISSUE THREAD

**Issue by hunshenshi** [AliyunContainerService/log-pilot#165]
fluentd关于容器log的pos是记录在`pos_file /pilot/pos/{{ $.containerId }}.{{ .Name }}.pos`这里，但是在pod中容器重启之后log所在的目录不会变，容器id发生了变化，所以pos也就发生了变化，fluentd就会对重启之后的log进行重采集，造成log采集重复，有没有遇到这种情况，反正我遇到了

**Comment by chenquanzhao** [comment]
@hunshenshi 我们处理下，也欢迎提PR

**Comment by hunshenshi** [comment]
`{{if index $.container "k8s_pod"}}{{ index $.container "k8s_pod" }}{{else}}{{ $.containerId }}{{end}}`
我改成这样了，判断了下

**Comment by hunshenshi** [comment]
@chenquanzhao 如果这样可以到话，我就提个PR

**Comment by ZP-AlwaysWin** [comment]
> fluentd关于容器log的pos是记录在`pos_file /pilot/pos/{{ $.containerId }}.{{ .Name }}.pos`这里，但是在pod中容器重启之后log所在的目录不会变，容器id发生了变化，所以pos也就发生了变化，fluentd就会对重启之后的log进行重采集，造成log采集重复，有没有遇到这种情况，反正我遇到了

这个log所在的目录应该会变吧！因为容器的ID变了。
![image](https://user-images.githubusercontent.com/23489782/86002902-9bf01880-ba43-11ea-8f54-67f5f282278f.png)
