### ISSUE TITLE
建议：filebeat的参数中可以指定topic

### ISSUE THREAD

**Issue by wajika** [AliyunContainerService/log-pilot#170]
我看到在config.filebeat文件中有topic的变量，为什么不拿出来做可变参数呢？
output.kafka:
    hosts: [$KAFKA_BROKERS]
    topic: '%{[topic]}'    ==》是否改为大写就可以用了？

**Comment by chenquanzhao** [comment]
@wajika  topic可直接在tags里topic=xxx来指定即可

**Comment by wajika** [comment]
> @wajika topic可直接在tags里topic=xxx来指定即可

好的

**Comment by chengzixs** [comment]
> @wajika topic可直接在tags里topic=xxx来指定即可

能生效么 topic=ccp-elk 没有生效
