### ISSUE TITLE
严重bug： kubernetes中log-pilot会导致无法删除其他pod

### ISSUE THREAD

**Issue by kingaceck** [AliyunContainerService/log-pilot#171]
在log-pilot.yml中挂载主机的根目录到容器的/root目录，如下：
- name: root
          mountPath: /host
          readOnly: true

- name: root
        hostPath:
          path: /
启动守护进程log-pilot后，删除其他应用的pod时一直无法删除(kubectl delete pod ...)，pod状态一直处于Terminating状态。此时删除守护进程log-pilot后其他pod能正常删除。
或者将log-pilot.yml中挂载根目录注释掉也能正常删除其他pod，但无法正常采集日志。

经反复测试挂载主机根目录到log-pilot的/root目录后，会导致无法删除其他pod的情况，请问如何解决？kubernetes版本为1.11。

执行kubectl delete pod ...命令后，kubelet日志如下：
**Error**: "UnmountVolume.TearDown failed for volume \"default-token-lwphf\" (UniqueName: \"kubernetes.io/secret/7ea34de2-1482-11e9-8933-525400ea54ff-default-token-lwphf\") pod \"7ea34de2-1482-11e9-8933-525400ea54ff\" (UID: \"7ea34de2-1482-11e9-8933-525400ea54ff\") : **remove** /var/lib/kubelet/pods/7ea34de2-1482-11e9-8933-525400ea54ff/volumes/kubernetes.io~secret/default-token-lwphf: **device or resource busy**"

查找发现pilot占用了以上日志中无法删除的文件：
27765	mnt:[4026532391]	/pilot/pilot-template/pilot/filebeat.tpl-base/host-log-leveldebug	/host/var/lib/kubelet/pods/7ea34de2-1482-11e9-8933-525400ea54ff/volumes/kubernetes.io~secret/default-token-lwphf

27816	mnt:[4026532391]	/usr/bin/filebeat-c/etc/filebeat/filebeat.yml	/host/var/lib/kubelet/pods/7ea34de2-1482-11e9-8933-525400ea54ff/volumes/kubernetes.io~secret/default-token-lwphf

**Comment by BSWANG** [comment]
如果是centos/rhel，升级到7.4以上版本配置下fs.may_detach_mounts内核参数=1就行了

其他发行版升级到4.4以上内核也可以解决

**Comment by silenceper** [comment]
> 如果是centos/rhel，升级到7.4以上版本配置下fs.may_detach_mounts内核参数=1就行了
> 
> 其他发行版升级到4.4以上内核也可以解决

对于centos 7.4 版本以下的版本，如何处理？有没有临时解决办法
