### ISSUE TITLE
in log *: /home/logs/*.log is not mount on host怎么解决

### ISSUE THREAD

**Issue by ididy** [AliyunContainerService/log-pilot#173]
`
{
        "volumeMounts": [
              {
                "name": "buildserver-log",
                "mountPath": "/home/logs"
              }
            ]
        ],
        "volumes": [
          {
            "name": "buildserver-log",
            "emptyDir": {}
          }
        ],
}
`

**Comment by ididy** [comment]
已解决

**Comment by wajika** [comment]
> 已解决

挂个emptyDir就可以了吗？

**Comment by tttlkkkl** [comment]
@ididy 怎么解决的，我也遇到这个问题了。看到麻烦告知一下，谢谢。

**Comment by tttlkkkl** [comment]
这个问题是从日志文件收集时，log-pilot 没有挂载日志目录导致的。可以通过挂载主机目录或者volume使日志文件所在目录与log-pilot容器实现共享。
