### ISSUE TITLE
【请教】如果使用filebeat的modules采集traefik的日志

### ISSUE THREAD

**Issue by xingshao-ye** [AliyunContainerService/log-pilot#178]
filebeat集成模块索引，请教如何使用registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.6-filebeat使用modules采集traefik的日志

**Comment by joeylin** [comment]
traefik有什么特殊的地方么？直接通过配置日志路径不行？

**Comment by chenquanzhao** [comment]
@xingshao-ye 直接配置采集traefik容器的stdout日志或者文件日志即可
