### ISSUE TITLE
[请教]是否支持发送到logstash?

### ISSUE THREAD

**Issue by Dannyvon** [AliyunContainerService/log-pilot#180]
我尝试在Kubernetes的log-pilot.yaml 增加 logstash,但仍然无法成功.

          - name: "LOGGING_OUTPUT"
            value: "logstash"
          - name: "LOGSTASH_HOST"
            value: "192.168.1.1"
          - name: "LOGSTASH_PORT"
            value: "15044"

**Comment by chenquanzhao** [comment]
@Dannyvon 可以看下/var/log/filebeat/下filebeat日志

**Comment by chiangwei** [comment]
不支持logstash吧？

**Comment by EricBatty** [comment]
支持了吗？怎么写的？
