### ISSUE TITLE
请问下为啥我配置deployment 始终不生效呀,pod里面配置是没有问题的。es能收集到日志

### ISSUE THREAD

**Issue by hyliuzhe** [AliyunContainerService/log-pilot#189]
env:
     - name: aliyun_logs_catalinatomcatlp
       value: "stdout"                                             ##采集标准输出日志
     - name: aliyun_logs_accesstomcatlp
       value: "/usr/local/tomcat/logs/catalina.*.log"

这是我的k8s yaml配置

**Comment by chenquanzhao** [comment]
@hyliuzhe 采集stdout和容器内文件日志的索引名配置成不一样的索引
