### ISSUE TITLE
追问一下-在K8s容器里面需要什么特殊权限么？

### ISSUE THREAD

**Issue by rockjing** [AliyunContainerService/log-pilot#192]
之前有人问过其在swarm模式下面无法运行。
https://github.com/AliyunContainerService/log-pilot/issues/51
那么，在k8s里面运行会有特殊的权限问题么？
我们现在的容器都在docker swarm模式下面。

**Comment by chenquanzhao** [comment]
@rockjing K8S里只要配置下SYS_ADMIN权限即可

**Comment by rockjing** [comment]
@chenquanzhao  谢谢！
