### ISSUE TITLE
请教一个关于阿里云sls采集的问题

### ISSUE THREAD

**Issue by tttlkkkl** [AliyunContainerService/log-pilot#193]
log-pilot 传输至阿里云sls时都是通过公网传输的吗？那么是否配置 SSL_VERIFY 的值为 true 是否可以保证数据被加密传输呢？因为日志数据中包含很多敏感信息，所以数据安全很重要。log-pilot 很好用几乎零配置，我决定使用它采集docker日志数据到阿里云sls，但是在数据传输安全性上有些担忧，有空请帮我解答一下。谢谢。

**Comment by chenquanzhao** [comment]
@tttlkkkl 您是要在阿里云的容器K8S集群里来采集POD日志到日志服务SLS吗？

**Comment by rockjing** [comment]
我估计， @tttlkkkl 是有一个自建的k8s, 所以才提这种问题。

**Comment by tttlkkkl** [comment]
是这样的，我有两个swarm服务集群，一个面向境内用户一个面向境外用户，一个在深圳一个在香港（两地机器已实现VPC联通），用阿里云日志服务提供的默认日志收集器貌似只能同地域收集日志，所以我用log-pilot来对日志进行统一收集，能够达到预期——将日志统一采集到同一个project。但是我希望日志上传能走内网或者走公网的时候能被加密传输。我猜测log-pilot走的应该是公网连接，请问在这情况下数据传输安全有没有保障呢？
@chenquanzhao @rockjing

**Comment by chenquanzhao** [comment]
@tttlkkkl  日志服务应该支持日志同步的
