### ISSUE TITLE
有在 k8s 中部署 log-pilot+elasticsearch+kibana 的文档吗?

### ISSUE THREAD

**Issue by m2acgi** [AliyunContainerService/log-pilot#198]
如题。https://help.aliyun.com/document_detail/68264.html#h2-url-4 这个文档的 elasticsearch, kibana 版本太老了。

**Comment by chenquanzhao** [comment]
@m2acgi 可升级下YAML的镜像版本

**Comment by m2acgi** [comment]
更改镜像版本，yaml 中的其它的参数兼容吗？

**Comment by yudar1024** [comment]
能支持7.x系列的ES吗，看源码fiebeat的镜像版本还是6.1的
