### ISSUE TITLE
和阿里云SLS搭配使用时怎么指定Logstore？

### ISSUE THREAD

**Issue by symfu** [AliyunContainerService/log-pilot#199]
文档里只提到 ALIYUNSLS_PROJECT，但是搜遍全项目，没看到哪里指定 LogStore 的，收集到的日志到底是发送到哪个 LogStore？

**Comment by symfu** [comment]
好吧，看文档找到了，看走眼了，我还以为会有ALIYUNSLS_LOGSTORE这样的变量。

**Comment by Carl-Xiao** [comment]
您好~想请教下ALIYUNSLS_LOGSTORE是怎么解决的
