### ISSUE TITLE
log-pilot-filebeat如何根据目录采集多种格式的日志

### ISSUE THREAD

**Issue by gmingkai** [AliyunContainerService/log-pilot#201]
如下场景：

#### 日志一：

- 路径：/tmp/toaeed/xxx.log

- 格式：2019-05-23 16:18:00,015 [activityOpenTaskHandler_Worker-1] 。。。

#### 日志二：

- 路径：/tmp/access/xxx.log

- 格式：[2019-05-23 16:16:39.239] [INFO]。。。

我想根据日志收集的目录判断是否需要在filebeat的对应配置里加入多行合并的规则，

filebeat.tpl里该怎么做判断呢？尝试过{{gt .HostDir "access" }}判断是否包含字符串，没成功。请指教，谢谢！

**Comment by gmingkai** [comment]
如何判断HostDir是否包含某个关键字呢？

**Comment by Darren-wh** [comment]
这个你定义不同索引，就可以实现不同目录日志采集。
         - name: aliyun_logs_tomcat-dev-stdout
           value: stdout
         - name: aliyun_logs_tomcat-dev-access
           value:  /data/tomcat/logs/*access*.txt
         - name: aliyun_logs_tomcat-dev-applog
           value: /data/tomcat/logs/app/*.log
这边就定义了3个目录。

**Comment by chenquanzhao** [comment]
@gmingkai 可以参考下golang的template语法
