### ISSUE TITLE
扔到K8S里面，使用daemonset方式部署，pod重启的话，日志会重复

### ISSUE THREAD

**Issue by tongpaopao** [AliyunContainerService/log-pilot#204]
当pod重启的时候，K8S会重命名这个container的名称，直接对在container的名称后面有一个_1的后缀。
pilot会生成一个相同目录的filebeat配置文件。
这个配置文件收集的目录与重启之前的pod重叠。如果是全量收集的话，filebeat会直接把这个日志文件收集2份。传给下游

**Comment by Darren-wh** [comment]
重启不是里面的服务重启吗？怎么会变成pod 重启？

**Comment by tongpaopao** [comment]
当你的java的应用crash掉了。这个java应用是在pod里面的，K8S会自动的把这个crash的pod拉起。但是k8s给pod启动的container添加了一个新的name
比如原来是
k8s_POD_prometheus-node-exporter-bqzb7_monitoring_7622c58e-f482-11e8-806f-d0946622aef5_0
这个pod重启以后name就变成
k8s_POD_prometheus-node-exporter-bqzb7_monitoring_7622c58e-f482-11e8-806f-d0946622aef5_1
但是有一段检测时间，这个时候日志就会重复了。

**Comment by mmmmmmmxl** [comment]
配置的时候日志路径挂载使用empty dir，否则日志持久化会重复采集

**Comment by wangycc** [comment]
@mmmmmmmxl 服务重新发布后，log-pilot采集不到，需要重启服务才行，不知是什么原因

**Comment by mmmmmmmxl** [comment]
@wangycc  如果用的是filebeat， 到pod /var/logs/filebeat看看filebeat日志，fluentd同理

**Comment by feiyu563** [comment]
这似乎是个bug, https://github.com/AliyunContainerService/log-pilot/pull/218

**Comment by chenquanzhao** [comment]
@feiyu563 已Merge，感谢！
