### ISSUE TITLE
类似 filebeat  中的 document_type 怎么配置

### ISSUE THREAD

**Issue by ming200825** [AliyunContainerService/log-pilot#226]
类似 filebeat  中的 document_type 怎么配置

**Comment by ming200825** [comment]
aliyun.logs.$name.tags：上报日志时，额外增加的字段，格式为 k1=v1,k2=v2，每个 key-value 之间使用逗号分隔，例如 aliyun.logs.access.tags="name=hello,stage=test"，上报到存储的日志里就会出现 name 字段和 stage 字段。
如果使用 ElasticSearch 作为日志存储，target 这个 tag 具有特殊含义，表示 ElasticSearch 里对应的 index。


应该是用这个方法 加 _type字段 是吗

**Comment by chenquanzhao** [comment]
@ming200825  document_type filebeat已不再支持配置

**Comment by ktpktr0** [comment]
经过测试，加了tag后，无法读取日志文件

log-pilot输出至logstash
log-pilot版本： log-pilot:0.9.7-filebeat
示例：
docker run -it --rm -p 10080:8080 -v /usr/local/tomcat/logs --label aliyun.logs.catalina=stdout --label aliyun.logs.access=/usr/local/tomcat/logs/localhost_access_log.*.txt --label aliyun.logs.catalina.tags="type=tomcatcatalina" --label aliyun.logs.access.tags="type=tomcataccess" tomcat

测试结果，只能读取stdout的tag，而日志文件的tag无法读取。
