### ISSUE TITLE
关于以日期开头的多行日志怎么收集呢

### ISSUE THREAD

**Issue by Linuxbody** [AliyunContainerService/log-pilot#233]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/9931457/63151687-a3315200-c03c-11e9-9956-289935143949.png">

**Comment by Linuxbody** [comment]
这就是一个信息，但是被分开成多行收集了

**Comment by JDalready** [comment]
解决了吗

**Comment by xuhengpw** [comment]
m

**Comment by chenquanzhao** [comment]
@Linuxbody 可参考下 #121
