### ISSUE TITLE
log-pilot:0.9.6-filebeat  filebeat registry文件不清理过期log state

### ISSUE THREAD

**Issue by yuline** [AliyunContainerService/log-pilot#245]
使用log-pilot:0.9.6-filebeat 发现filebeat的registry文件（/var/lib/filebeat/registry）越来越大，检查后发现已经删除的文件state还一直保留在registry中，比如：

/pilot # grep -o inke-push-live-ip2city-tx-bj3-75ddf874f6-shnxs/access-2019092118.log /var/lib/filebeat/registry
inke-push-live-ip2city-tx-bj3-75ddf874f6-shnxs/access-2019092118.log
/pilot # ls /host/a8root/container_logs/inke-push-live-ip2city-tx-bj3-75ddf874f6-shnxs/access-2019092118.log
ls: /host/a8root/container_logs/inke-push-live-ip2city-tx-bj3-75ddf874f6-shnxs/access-2019092118.log: No such file or directory

**Comment by silenceper** [comment]
同样的问题，请问解决了吗 @yuline
