### ISSUE TITLE
pilot不能处理多行日志

### ISSUE THREAD

**Issue by zxkane** [AliyunContainerService/log-pilot#25]
正在使用`pilot`通过正则表达式来预处理日志。但日志中含Java异常的多行日志无法被正确处理。多行的堆栈信息被丢弃了。

`logtail`中有选项表明日志是否是多行日志，通过正则表达式匹配日志的开头。

**Comment by jzwlqx** [comment]
这个支持起来实现并不算复杂，但是配置会很麻烦，尤其是日志内容里既有格式化的单行日志，也有异常栈这种多行日志。一般不建议使用多行日志。推荐的方式是使用context log，在一行日志里包含能关联上下文日志的关键字，比如请求的uid或者request id。使用关键字可以关联出所有需要的信息。

Exception Stack是个特殊情况，可以尝试的办法是把异常栈写成一行，或者在message里包含更多的信息。

**Comment by zxkane** [comment]
Java的Logger库（包括最流行的slf4j/logback）不支持将Exception Stack写成一行。

**Comment by baotong** [comment]
对异常栈log 有什么好办法吗？

**Comment by dnmidi** [comment]
怎么没下文了？
怎么解决这个?

**Comment by zxkane** [comment]
我们现在的解法是，

1. 用logstash logback appender,把日志写成json格式输出到stdout
2. 直接用docker `fluentd` logdriver 归集日志

另外，阿里的日志服务新有了logback appender。如果用阿里的日志服务，可以用这个库来归集
