### ISSUE TITLE
log-pilot filebeat 采集 日志时间的问题

### ISSUE THREAD

**Issue by iventong** [AliyunContainerService/log-pilot#261]
提交保存到 es 通过 kibana查看到的时间是日志提交到存储的时间不是发生的事件，所以日志顺序存在混乱，该如何处理

**Comment by wangycc** [comment]
logstash 通过date模块解析日志日志为@timestap时间

**Comment by iventong** [comment]
通过配置Pipelines提取日志时间，已解决
