### ISSUE TITLE
log-pilot输出到logstash，怎么创建多个索引?

### ISSUE THREAD

**Issue by ktpktr0** [AliyunContainerService/log-pilot#270]
例如，我有tomcat和nginx的日志都被log-pilot收集，如果直接输出到es就会创建多个索引
但是有些日志需要logstah进行解析，因此输出到logstash。但我不知道怎么区分不同的日志来创建相应索引？，下面是我期望的结果

output {
        if "nginx" in [tags] {
                elasticsearch {
                        hosts => ["127.0.0.1:9200"]
                        manage_template => true
                        index => "nginx-%{+YYYY.MM.dd}"
        }
        }
        if "system" in [tags] {
                elasticsearch {
                        hosts => ["127.0.0.1:9200"]
                        manage_template => false
                        index => "system-%{+YYYY.MM.dd}"
        }

**Comment by ktpktr0** [comment]
我尝试这样的好像不行
1、需要收集日志的容器标签
--label aliyun.logs.catalina=stdout --label aliyun.logs.access=/usr/local/tomcat/logs/localhost_access_log.*.txt --label aliyun_logs_catalina_tags="tags=tomcatcatalina" --label aliyun_logs_catalina_tags="tags=tomcataccess"

2、配置logstash

output {
        if "tomcataccess" in [tags] {
                elasticsearch {
                        hosts => ["127.0.0.1:9200"]
                        manage_template => true
                        index => "tomcat-access-%{+YYYY.MM.dd}"
        }
        }
        if "tomcatcatalina" in [tags] {
                elasticsearch {
                        hosts => ["127.0.0.1:9200"]
                        manage_template => false
                        index => "tomcat-catalina-%{+YYYY.MM.dd}"
        }
    }
}

**Comment by ktpktr0** [comment]
I got it

**Comment by totemofwolf** [comment]
> I got it

怎么解决的？
