### ISSUE TITLE
如何收集Java堆栈信息

### ISSUE THREAD

**Issue by standup-jb** [AliyunContainerService/log-pilot#284]
通过log-pilot 收集到的数据是按照行收集的。但是其实Java的堆栈数据应该算是一条。请问一下有没有什么办法把堆栈信息当成一条数据收集。

**Comment by culyzhao** [comment]
同问

**Comment by penetest** [comment]
参考 filebeat 多行日志收集

**Comment by standup-jb** [comment]
> 参考 filebeat 多行日志收集
尝试过。不太行。有没有比较具体的实现方式和教程

**Comment by liqilong2017** [comment]
hello 
你这个问题解决了吗？？

**Comment by penetest** [comment]
参考 filebeat 多行日志收集




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liqilong2017"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 下午2:28
收件人: "AliyunContainerService/log-pilot"<log-pilot@noreply.github.com&gt;; 
抄送: "macalzheng"<1533633943@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [AliyunContainerService/log-pilot] 如何收集Java堆栈信息 (#284)





 
hello
 你这个问题解决了吗？？

**Comment by 445990772** [comment]
> 参考 filebeat 多行日志收集
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liqilong2017"<notifications@github.com&gt;; 发送时间: 2020年9月16日(星期三) 下午2:28 收件人: "AliyunContainerService/log-pilot"<log-pilot@noreply.github.com&gt;; 抄送: "macalzheng"<1533633943@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [AliyunContainerService/log-pilot] 如何收集Java堆栈信息 (#284) hello 你这个问题解决了吗？？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

怎么配置pilot的参数呢？
