### ISSUE TITLE
按首页readme已经不能拉到依赖image,需要更新基础镜像

### ISSUE THREAD

**Issue by gaoxiang9457** [AliyunContainerService/log-pilot#304]
按首页readme已经不能拉到依赖image,需要更新基础镜像

**Comment by hzliangbin** [comment]
> 按首页readme已经不能拉到依赖image,需要更新基础镜像

是哪个镜像获取不到？我这里是ok的。

**Comment by Zhang21** [comment]
项目右边的release里，有最先的版本。

**Comment by gaoxiang9457** [comment]
可能是镜像仓库不稳定,今天试了两个环境都可以拉取到了,打扰了!
