### ISSUE TITLE
监听docker的stop事件

### ISSUE THREAD

**Issue by yybear** [AliyunContainerService/log-pilot#39]
目前pilot监听的是start和destroy事件。我测试发现在swarm service升级镜像（可能是做的最多的操作），触发不了destroy事件： docker service update    --- create 新容器-> kill -> die -> stop -> start 新容器，destroy一般就是 docker service rm和 scale缩容时触发。

**Comment by BSWANG** [comment]
![image](https://user-images.githubusercontent.com/3598874/28010407-67adeb7e-6591-11e7-8eca-a811185c719b.png)

测试了一下，`swarm mode`中确实如此，我觉得可以把`destroy`事件换成`stop`事件，欢迎提交PR.

**Comment by chenquanzhao** [comment]
@BSWANG @yybear LogPilot的日志采集配置会跟容器的生命周期保持同步，被stop后容器依然存在，待被destroy后也会自动清除日志采集配置的
