### ISSUE TITLE
容器事件丢失问题  

### ISSUE THREAD

**Issue by yybear** [AliyunContainerService/log-pilot#40]
pilot.go 的watch函数，先获取所有容器处理然后才会监听docker container事件。
虽然processAllContainers会很快，但是如果容器很多，或者StartFluentd花费一定时间的话，中间可能有些容器创建事件会丢，理论上是可能的。

所以在processAllContainers之前保存一个时间戳，监听时加个since应该更好点。

**Comment by qq676596084** [comment]
现在还是存在这个问题~没得到解决 有没有什么解决办法

**Comment by chenquanzhao** [comment]
@qq676596084 已优化容器事件监听机制，可以升级到最新版本：https://github.com/AliyunContainerService/log-pilot/releases
