### ISSUE TITLE
请问如何将一个索引按照日期进行切分

### ISSUE THREAD

**Issue by apaul030515** [AliyunContainerService/log-pilot#42]
您好，

根据文档的步骤，将日志生成为索引access,请问如何将一个索引按照日期进行切分，切分成access-%Y%m%d的格式，是否有启动参数?

**Comment by modeyang** [comment]
+1

**Comment by modeyang** [comment]
https://github.com/uken/fluent-plugin-elasticsearch#target_index_key  是不是需要在代码里将target参数写成类似$target-2014.12.19这样的格式

**Comment by vihan-zrh** [comment]
创建索引的时候写access-*
time-field name选@timestartmp
然后es里查看索引curl 'localhost:9200/_cat/indices?v',都是按日期的.类似:access-2018.03.23

**Comment by xingshao-ye** [comment]
您好，按照上面的方法没实现把elasticsearch的文档按日期切分，请教要如何实现把收集到的日志存在elasticsearch时文档按日期切分？

**Comment by xingshao-ye** [comment]
使用latest的版本已解决按日期切割的问题，谢谢！

**Comment by cheng0214** [comment]
@xingshao-ye  请教一下如何配置
