### ISSUE TITLE
重启 fluentd-pilot 导致日志重复收集

### ISSUE THREAD

**Issue by eastNan** [AliyunContainerService/log-pilot#62]
问题描述
你好，在使用 fluentd-pilot 收集容器日志过程中，发现如果 重启 fluentd-pilot容器，将导致'目标容器'日志重复收集，fluentd-pilot 重启次数与'目标日志'重复数量成正比;

例如，使用 fluentd-pilot 收集 nginx容器的日志，因为重启过 fluentd-pilot 3次，则 nginx 容器的日志收集了 3次;

2017-09-05 18:23:34.000	20da0f89abbb
10.0.x.23 - - [05/Sep/2017:18:23:34 +0800] "HEAD / HTTP/1.1" 200 0 "-" "curl/7.35.0" 123.124.21x.21x, 150.138.21x.13x 0.015
2017-09-05 18:23:34.000	20da0f89abbb
10.0.x.23 - - [05/Sep/2017:18:23:34 +0800] "HEAD / HTTP/1.1" 200 0 "-" "curl/7.35.0" 123.124.21x.21x, 150.138.21x.13x 0.015
2017-09-05 18:23:34.000	20da0f89abbb
10.0.x.23 - - [05/Sep/2017:18:23:34 +0800] "HEAD / HTTP/1.1" 200 0 "-" "curl/7.35.0" 123.124.21x.21x, 150.138.21x.13x 0.015

环境
17.05.0-ce On CentOS 7.3 

命令
docker run --name fluentd-pilot -itd \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /etc/localtime:/etc/localtime \
    -v /:/host \
    -e TZ=Asia/Chongqing \
    -e FLUENTD_OUTPUT=graylog \
    -e GRAYLOG_HOST=efg.test.idc \
    -e GRAYLOG_PORT=12201 \
    registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:0.0.3

请帮忙看下，谢谢。

**Comment by BSWANG** [comment]
请使用最新的fluentd-pilot尝试下看是否还有问题

**Comment by zongmry** [comment]
测试使用 fluentd-pilot:latest ，问题是存在，可见截图1

![fluentd-1](https://user-images.githubusercontent.com/16666083/30688048-b45bdffc-9eef-11e7-9939-60310c5dbdaa.png)

环境补充
1. 启动  fluentd-pilot 容器时，docker 主机已经运行其它的容器;
2. 组合包括，fluentd-pilot 负责收集，graylog 负责展现，elasticsearch 负责存储与索引，
    除了使用 fluentd-pilot 收集容器日志外，另外还使用 rsyslog 推送系统日志信息至 graylog ，但是 rsyslog 推送的信息没有发现重复，可见截图2;

![rsyslog-1](https://user-images.githubusercontent.com/16666083/30688408-a62d8376-9ef0-11e7-92e5-f8de465801d7.png)

谢谢

**Comment by okjesse** [comment]
的确会这样，我用这个监控spring boot docker的日志也是一样会

**Comment by MicroKernelXulj** [comment]
楼主，你是咋用graylog监控的，我也这样搞的为啥不行
![image](https://user-images.githubusercontent.com/16525577/36932320-5ba621ae-1f02-11e8-8dec-25fdf274a5e0.png)

**Comment by chenquanzhao** [comment]
可以使用0.9.5-filebeat版本的镜像
