### ISSUE TITLE
我的fluentd启动后接受日志后 一直报错[error]: closed stream，[error]: suppressed same stacktrace

### ISSUE THREAD

**Issue by PeterZhai00** [AliyunContainerService/log-pilot#71]
我的fluentd启动后接受日志后 一直报错[error]: closed stream，[error]: suppressed same stacktrace

**Comment by BSWANG** [comment]
这个报错看不出什么问题，可以尝试把最初的stacktrace贴上来，一般是配置的错误导致的

**Comment by PeterZhai00** [comment]
version: '2'
services:
  pilot01:
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:latest
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: '9200'
      FLUENTD_OUTPUT: elasticsearch
    external_links:
    - es-cluster/es-master:elasticsearch
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /:/host
    labels:
      aliyun.global: 'true'

**Comment by PeterZhai00** [comment]
2017-12-18 02:59:32 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:32  2017-12-18 02:59:32 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:332017-12-18 02:59:33 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:33  2017-12-18 02:59:33 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:342017-12-18 02:59:34 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:34  2017-12-18 02:59:34 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:352017-12-18 02:59:35 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:35  2017-12-18 02:59:35 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:362017-12-18 02:59:36 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:36  2017-12-18 02:59:36 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:372017-12-18 02:59:37 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:37  2017-12-18 02:59:37 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:382017-12-18 02:59:38 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:38  2017-12-18 02:59:38 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:392017-12-18 02:59:39 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:39  2017-12-18 02:59:39 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:402017-12-18 02:59:40 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:40  2017-12-18 02:59:40 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:412017-12-18 02:59:41 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:41  2017-12-18 02:59:41 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:422017-12-18 02:59:42 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:42  2017-12-18 02:59:42 +0000 [error]: #0 suppressed same stacktrace
2017/12/18 上午10:59:432017-12-18 02:59:43 +0000 [error]: #0 Is a directory @ io_getpartial - /host/.
2017/12/18 上午10:59:43  2017-12-18 02:59:43 +0000 [error]: #0 suppressed same stacktrace

**Comment by PeterZhai00** [comment]
输出一直是这些 怎么回事 但是可以正常接受日志

**Comment by lightning130** [comment]
我也发现有这个问题，日志可以正常输出到es，另外还有一个问题，aliyun.logs.tags = xxx 这个在es里面并没有生成index，不知道是我没有配置对还是大家也有这个问题

**Comment by jeanhao** [comment]
我出现这个错误因为docker日志驱动位置为非json-file，该回来就正常了

**Comment by crystonesc** [comment]
我也遇到这个问题了，不知道怎么解决呢

**Comment by mayiwei** [comment]
> 我也遇到这个问题了，不知道怎么解决呢

查看一下你的 kafka 版本，再和 [https://github.com/zendesk/ruby-kafka/blob/master/README.md](https://github.com/zendesk/ruby-kafka/blob/master/README.md) 里的版本对照一下，做相应更新。
