### ISSUE TITLE
日志解析问题

### ISSUE THREAD

**Issue by kingsqv** [AliyunContainerService/log-pilot#72]
fluentd 收集docker console 日志 实际上是读取，docker 容器的json.log文件，这种日志docker 会在外层加上log 字段 ，如：
log:  {"appmsg":"","category":"access","clientIp":"1.1.1.1","contentLen":0,"duration":12,"env":"dddd","hostname":"1111","level":"info","method":"GET","requestId":"1.1.1.1","status":200,"tag":"222","time":"2017-12-29T05:46:50.62Z","url":"2222","ver":"0.0.3"}
如何把里面的字段也都按json格式显示呢。

**Comment by mengskysama** [comment]
这个是我另外写的一个中间件，你看看有没有帮助https://github.com/mengskysama/fluentd2sls
