### ISSUE TITLE
java exception被分成多行收集了，有什么好办法合并吗

### ISSUE THREAD

**Issue by jushiyuan** [AliyunContainerService/log-pilot#74]
java exception被分成多行收集了，有什么好办法合并吗

**Comment by aiwantaozi** [comment]
之前用过这个fluentd的插件来合并多行的java exception，配置比较简单 https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions

**Comment by jushiyuan** [comment]
@aiwantaozi 这个对于fluentd-pilot也有用吗，fluentd-pilot是基于fluentd开发的嘛
