### ISSUE TITLE
k8s中日志收集延迟高，不实时

### ISSUE THREAD

**Issue by jushiyuan** [AliyunContainerService/log-pilot#77]
最新版registry.cn-hangzhou.aliyuncs.com/acs-sample/fluentd-pilot:latest日志收集延迟很高，过几分钟才能看到，registry.cn-hangzhou.aliyuncs.com/wangbs/fluentd-pilot:latest镜像没有这个问题，是收集机制改变了吗？

**Comment by jushiyuan** [comment]
使用的是elasticsearch

**Comment by chenqz1987** [comment]
可以在fluentd-pilot里配置下环境变量试下：
FLUENTD_FLUSH_MODE: immediate

**Comment by jushiyuan** [comment]
@chenqz1987 不行，还是延迟

**Comment by zzswang** [comment]
@jushiyuan 请教 延时问题怎么解决的？
