### ISSUE TITLE
容器启动报错

### ISSUE THREAD

**Issue by sentrychen** [AliyunContainerService/log-pilot#78]
2018/1/16 下午5:26:17umount: can't unmount /host/var/lib/docker/containers/e7fac59793d8cc7d097b57418775bb7e6781a8e8c0706063f5b0d6e6f2011e20/shm: Operation not permitted
2018/1/16 下午5:26:17Traceback (most recent call last):
2018/1/16 下午5:26:17  File "/pilot/entrypoint", line 40, in <module>
2018/1/16 下午5:26:17    cleanup()
2018/1/16 下午5:26:17  File "/pilot/entrypoint", line 30, in cleanup
2018/1/16 下午5:26:17    umount(volume)
2018/1/16 下午5:26:17  File "/pilot/entrypoint", line 14, in umount
2018/1/16 下午5:26:17    subprocess.check_call('umount -l %s' % volume, shell=True)
2018/1/16 下午5:26:17  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
2018/1/16 下午5:26:17    raise CalledProcessError(retcode, cmd)
2018/1/16 下午5:26:17subprocess.CalledProcessError: Command 'umount -l /host/var/lib/docker/containers/e7fac59793d8cc7d097b57418775bb7e6781a8e8c0706063f5b0d6e6f2011e20/shm' returned non-zero exit status 1

**Comment by suyuan1203** [comment]
见：https://github.com/AliyunContainerService/fluentd-pilot/issues/76
fluentd-pilot需要运行在privileged模式
