### ISSUE TITLE
fluentd文件归档问题

### ISSUE THREAD

**Issue by hombre9** [AliyunContainerService/log-pilot#83]
报错：
config error file="/etc/fluentd/fluentd.conf" error_class=Fluent::ConfigError error="Parameter 'path: /tmp/logs/${docker_service}/${docker_app}/${tag[2]}.%Y-%m-%d.log' doesn't have enough placeholders for keys docker_container"

问题：
使用file的output，请问类似这样的变量，${tag[2]}.%Y-%m-%d.log，${docker_service}如何传入

**Comment by jzwlqx** [comment]
在容器label上，path写的是容器内的路径，不会用到docker-app之类的变量，参考使用文档
