### ISSUE TITLE
日志可以收到但是偶尔报这个Unauthorized

### ISSUE THREAD

**Issue by Arvintian** [AliyunContainerService/log-pilot#85]
> 2018-03-16 03:06:55 +0000 [warn]: #0    Caught in puts logs: LogException:
{
    ErrorCode: Unauthorized
    ErrorMessage: denied by sts or ram, action: log:PostLogStoreLogs, resource: acs:log:cn-beijing:1841696975452027:project/xxx
    RequestId: ["5AAB34CFA3342560601902EC"]
}

> 2018-03-16 03:07:34 +0000 [warn]: #0    Caught in puts logs: LogException:
{
    ErrorCode: Unauthorized
    ErrorMessage: denied by sts or ram, action: log:PostLogStoreLogs, resource: acs:log:cn-beijing:1841696975452027:project/xxx
    RequestId: ["5AAB34F6A2A7DA204B102C8A"]
}

> 2018-03-16 03:09:07 +0000 [warn]: #0    Caught in puts logs: LogException:
{
    ErrorCode: Unauthorized
    ErrorMessage: denied by sts or ram, action: log:PostLogStoreLogs, resource: acs:log:cn-beijing:1841696975452027:project/xx
    RequestId: ["5AAB3553F8B331530E15CBB6"]
}

**Comment by Arvintian** [comment]
是不是和aliyun_sls_sdk这个gem有关呢？阿里同学看一下呗

**Comment by NominationP** [comment]
楼上的兄弟 解决了吗

**Comment by Arvintian** [comment]
@NominationP 没有解决，报的频率很低

**Comment by NominationP** [comment]
我发现使用频率很大的时候,会频繁出现

Arvin <notifications@github.com> 于2018年9月3日周一 下午3:33写道：
