### ISSUE TITLE
如何实现kubernetes的pod容器日志采集?

### ISSUE THREAD

**Issue by wklken** [AliyunContainerService/log-pilot#88]
kuberntes在直接apply一个deployment, 在pod中声明的labels并不会传递给containers

此时, 在上层pod中打的日志相关labels, 在docker containers并找不到.

那么, log-pilot是如何采集k8s相关的容器日志的呢? 我看源代码 https://github.com/AliyunContainerService/log-pilot/blob/master/pilot/pilot.go#L332:31 有从env中取, 是否可以通过这个解决?

**Comment by suyuan1203** [comment]
log-pilot没改名字前是通过env配置的，不是通过labels，不知道是不是代码已经修改过了

```
env:
      - name: "FLUENTD_OUTPUT"
         value: "aliyun_sls"
```

**Comment by suyuan1203** [comment]
应该是可以的，这个项目还叫fluentd-pilot的时候，通过类似这样的环境变量配置
```
aliyun_logs_prod: stdout
```

**Comment by chenqz1987** [comment]
k8s集群里通过env来配置

**Comment by wklken** [comment]
仔细读了下源码, env配置相关前缀的变量即可;
问题关闭, thx:)
