### ISSUE TITLE
log-pilot:0.9.2-filebeat  无法传输日志

### ISSUE THREAD

**Issue by xiongmingwu** [AliyunContainerService/log-pilot#90]
启动服务后发现日志未存储至ES中，查看日志发现如下ERROR信息：
![image](https://user-images.githubusercontent.com/31282628/37634158-587f8502-2c30-11e8-8068-560f21a849d3.png)
log-pilot容器中安装curl能正常访问ES API服务！烦请给个解决的方案，谢谢！

**Comment by chenqz1987** [comment]
新版本0.9.3-filebeat修复了这个问题，谢谢！

**Comment by xiongmingwu** [comment]
@chenqz1987 好的 谢谢！
