### ISSUE TITLE
./run 拉取镜像都报错了

### ISSUE THREAD

**Issue by lizibin** [AliyunContainerService/log-pilot#95]
![image](https://user-images.githubusercontent.com/25076569/38006811-1852d9d0-3279-11e8-871f-0e506923b641.png)

**Comment by chenqz1987** [comment]
默认是直接用的本地的pilot:latest镜像，可以下载一个registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.3-filebeat

**Comment by Jesyjun** [comment]
![default](https://user-images.githubusercontent.com/9194837/41710431-3aac4254-7578-11e8-9225-12c09404e521.PNG)

镜像可以运行 但是不能detect docker host

**Comment by chenquanzhao** [comment]
这个是因为您当前PATH中未设置$DOCKER_HOST变量
