### ISSUE TITLE
0.9.3-filebeat会把log-pilot容器自身的日志也存到elasticsearch中，请问如何屏蔽日志收集容器自身的日志

### ISSUE THREAD

**Issue by xingshao-ye** [AliyunContainerService/log-pilot#96]
应用场景：收集tomcat容器的应用日志
使用镜像：log-pilot: 0.9.3-filebeat
使用环境：

- log-pilot的docker-compose.yml

version: '2'
services:
  Log-Pilot-Filebeat-Docker-1:
    privileged: true
    image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.3-filebeat
    environment:
      FILEBEAT_OUTPUT: elasticsearch
      ELASTICSEARCH_HOST: 192.168.10.121
      ELASTICSEARCH_PORT: '9200'
    stdin_open: true
    volumes:
    - /:/host
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    labels:
      io.rancher.container.pull_image: always
      aliyun.global: 'true'

问题：在kibana中会有log-pilot的日志输出，如下：
@timestamp:March 29th 2018, 11:25:44.001 source:/host/home/docker/volumes/2a972985ed230649be9b46351e413b5b709726deac6f3b68639e953a43b26662/_data/warn.log offset:6,523 message:	at java.lang.Thread.run(Thread.java:748) prospector.type:log index:tomcat topic:tomcat docker_container:r-msyt-api-test-2-1-25-18-msyt-search-api-1-ae2ea5ac beat.name:5e45e7eb2b1f beat.hostname:5e45e7eb2b1f beat.version:6.1.1 _id:AWJvyjJyc0u5X8tarGUj _type:doc _index:tomcat-2018.03.29 _score: -

**Comment by chenqz1987** [comment]
默认是只会采集配置了aliyun.logs标签的容器的日志，您看看是否是配置路径里跟这些日志所在目录有重合？
